### ISSUE TITLE
Request for New Release that Includes Well-Known Type Support

### ISSUE THREAD

**Issue by luluz66** [planetscale/vtprotobuf#126]
I would love to use the well-known type support that's currently available in the main branch;  I've found that it offers substantial marshaling speed improvements for some of our Protobuf messages. 

The latest release, v0.5.0, was released back in September. Would it be feasible to have a new release incorporating this feature in the near future?

**Comment by howardjohn** [comment]
+1; without this users need to do `go get github.com/planetscale/vtprotobuf@main` explicitly if they import a project that uses vtprotobuf (and deal with the non-tagged release in go.mod).

This pushes vtprotobuf build issues onto users that don't (intentionally) use vtprotobuf, so would be very nice to have a v0.6.0 to ease this pain.

**Comment by vmg** [comment]
Will do a new release today! Sorry for the wait!

**Comment by vmg** [comment]
Done!

**Comment by howardjohn** [comment]
Thanks!
