### ISSUE TITLE
Question: grpc

### ISSUE THREAD

**Issue by srikrsna** [planetscale/vtprotobuf#16]
One of the features (which is on by default if features are not specified) is grpc. A quick look at the code and I can't seem to find any difference between the regular grpc plugin and the code generated vtprotobuf. Is there a plan to extends this to use say use pool for object creation in the future?

**Comment by vmg** [comment]
Hey @srikrsna! The GRPC plugin is still experimental, but it does already support using pools for object creation -- that's the whole point of it. It generates boilerplate code which is identical to the upstream GRPC compiler, but where any objects that have been configured to be memory pooled are allocated from a pool. Are you failing to see this behavior in practice, or did you just miss it while reviewing the implementation?

**Comment by srikrsna** [comment]
I added pool as an option to the features directly. I guess I need to explicitly specify pool option against the messages I want to pool. 

Thank you for the clarification!
