### ISSUE TITLE
Proto3 optional field support

### ISSUE THREAD

**Issue by jbub** [planetscale/vtprotobuf#2]
Hello, i have just tried running this generator on my proto3 files and it failed with:

`myproto.proto is a proto3 file that contains optional fields, but code generator protoc-gen-go-vtproto hasn't been updated to support optional fields in proto3. Please ask the owner of this code generator to support proto3 optional.--go-vtproto_out:`

Is optional field supported by this generator ?

Thanks

**Comment by vmg** [comment]
This is probably a legitimate bug. Let me see how involved it is to fix.

**Comment by vmg** [comment]
This was more involved than I thought. Feature is implemented in https://github.com/planetscale/vtprotobuf/pull/5 -- please test it on your local codebases. Vitess does not use optional fields at all.
