### ISSUE TITLE
Error compiling generated code with third party imports

### ISSUE THREAD

**Issue by gmather** [planetscale/vtprotobuf#6]
Hello,

I was looking to experiment with this and ran into the following error:

```
type *"google.golang.org/genproto/googleapis/rpc/status".Status has no field or method MarshalToSizedBufferVT
```

The protobuf files that are complaining import files like:

```
import "google/rpc/status.proto";
```

with messages that look like:
```
message TestMessage {
   google.rpc.Status status = 2;
}
```

The `google/rpc/status.proto` file is copied locally for the code generation, but the generated code is importing the Go module from `google.golang.org/genproto/googleapis/rpc/status` so it's not part of the vtproto generation steps.

Is this an issue that you've had to resolve or any suggestions on how to approach this?

**Comment by vmg** [comment]
Hiii @gmather! This is indeed a real issue. Right now the check for foreign imports is really naive:

https://github.com/planetscale/vtprotobuf/blob/main/features/marshal/marshalto.go#L629

I need to come up with a better way to perform this check. Let me think it through.

**Comment by elvizlai** [comment]
The related issue:
x.proto
```
syntax = "proto3";

package api.common;

option go_package          = "api/common";

import public "google/api/field_behavior.proto";
import public "google/api/httpbody.proto";
import public "google/protobuf/any.proto";
import public "google/protobuf/empty.proto";
import public "google/protobuf/field_mask.proto";
import public "google/protobuf/struct.proto";
import public "google/protobuf/timestamp.proto";
import public "google/protobuf/wrappers.proto";

message X {
}
```

The generated code has error: `v.SizeVT undefined (type *structpb.Value has no field or method SizeVT)`

**Comment by alexism** [comment]
I ran into that issue as well.
For the "foreign" test, instead of relying on the message full name, could we instead test the interfaces implemented by the messages? Similarly to what the gRPC codec does.

The test would be performed before invoking any `*VT` functions.

For example, for the "unmarshal" feature", the generated code could be something like:

```go
			if o, ok := interface{}(m.MY_FIELD).(interface{
				UnmarshalVT([]byte) error
			});ok{
				if err := o.UnmarshalVT(dAtA[iNdEx:postIndex]); err != nil {
					return err
				}
			}else{
				if err := proto.Unmarshal(dAtA[iNdEx:postIndex], m.MY_FIELD); err!=nil{
					return err
				}
			}
```

**Comment by vmg** [comment]
I like that suggestion! I've implemented it in https://github.com/planetscale/vtprotobuf/pull/7 -- can you guys give this a go and see if it works in your codebases?
