### ISSUE TITLE
Custom Tag Support 

### ISSUE THREAD

**Issue by zafeerk** [planetscale/vtprotobuf#68]
Does vtprotobuf provide custom tag support like gogoprotobuf? I can't seem to find any information about this online.

in a .proto file, with gogoprotobuf I can attach customized tags like: 

```
import "github.com/gogo/protobuf/gogoproto/gogo.proto";

option go_package                  = "events";
option (gogoproto.unmarshaler_all) = true;
option (gogoproto.sizer_all)       = true;
option (gogoproto.marshaler_all)   = true;

message Event {
  string AuctionID                               = 1 [(gogoproto.moretags) = 'gorm:"column:auction_id;type:VARCHAR(64);primary_key"'];
  int64  CampaignID                              = 2 [(gogoproto.moretags) = 'gorm:"column:campaign_id;type:BIGINT;index"'];
  int64  ImpIndex                                = 3 [(gogoproto.moretags) = 'gorm:"column:imp_index;type:INT"'];
  string DomainKey                               = 5 [(gogoproto.moretags) = 'gorm:"column:domain_key;type:VARCHAR(1024)"'];
```

Does vtprotobuf provide any support for anything like `gogoproto.moretags`?

**Comment by vmg** [comment]
Hey @zafeerk! As you can see on the documentation, the point of `vtprotobuf` is that it runs as a codegen plug-in on top of `protoc-gen-go`, so it doesn't actually modify the default generated ProtoBuf code and instead generates optimized runtimes that can be used optionally.

This has some advantages, such as the fact that the code in `vtprotobuf` is highly compatible with the upstream and easy to maintain, and some disadvantages, such as not being able to modify the generated code to add things like custom tags :cry:.

Sorry!
