### ISSUE TITLE
cut new release?

### ISSUE THREAD

**Issue by newhook** [planetscale/vtprotobuf#75]
Hey all, any chance of cutting a new release?

The latest version is 0.3.0 and a bunch of stuff has been added since then such as some of the documented options (pool and so on). Is the current main stable? Can a new release be made?

**Comment by vmg** [comment]
I'm cutting a new release today! Sorry for the delay!

**Comment by vmg** [comment]
`v0.4.0` has been tagged and released! Should include quite a few important bug fixes!

**Comment by newhook** [comment]
Thanks very much! As long time gogo proto users, we love this library!!
