### ISSUE TITLE
Replace sync.Pool with zeropool

### ISSUE THREAD

**Issue by jzelinskie** [planetscale/vtprotobuf#81]
Generated pool code currently uses [sync.Pool](https://github.com/planetscale/vtprotobuf/blob/main/features/pool/pool.go#L45) which is nice because there are no external dependencies.
However, there is a [small dependency](https://github.com/colega/zeropool) we use instead that avoids a known allocation issue with sync.Pool (and introduces type safety, but it doesn't really matter since this is generated code).

**Comment by mattrobenolt** [comment]
From their own README:

> It is approximately ~2x slower than sync.Pool if what you are storing are pointers: it doesn't make sense to pay the price in that case.

Seems this wouldn't make sense here even to the author. I haven't double checked, but I assume we're always storing pointers.

**Comment by vmg** [comment]
Yes, I don't think this applies here @jzelinskie. `zeropool` was designed for the common case where _slices_ (mostly byte slices in practice) are stored in a pool, which causes double allocations. But `vtprotobuf` stores pointers to structs in the pool, so the only thing we get by using `zeropool` is a performance loss!
