### ISSUE TITLE
Discussion on the use of codec

### ISSUE THREAD

**Issue by davygeek** [planetscale/vtprotobuf#9]
Does vtprotobuf supports the use of vtprotobuf and standard proto.Message in the same project (we can rely on the Pb. Go file generated by other projects); 
Our real scene is that the internal proto file uses vtprotobu to improve performance, and some other functions rely on the third-party pb.go file; The following error occurred during processing

```
stream is closed with error: xds: stream.Recv() failed: rpc error: code = Internal desc = grpc: error while marshaling: failed to marshal, message is *envoy_service_discovery_v3.DiscoveryRequest (missing vtprotobuf helpers)" func=goexit 
```

**Comment by vmg** [comment]
Hi @davygeek! It's very easy to support this use case, but you can't use the default GRPC codec that ships with the library.

The Vitess project has the same requirement and I simply implemented our own coded that targets the behavior we need: https://github.com/vitessio/vitess/blob/main/go/vt/servenv/grpc_codec.go

You'll need to do the same for your project. Cheers!

**Comment by davygeek** [comment]
@vmg thanks
